version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo uninstalling old version
      - npm uninstall -g @angular/cli
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
      - echo Installing project dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running lint...
      - npm run lint || echo "Lint warnings ignored"

  build:
    commands:
      - echo Building the Angular project...
      - ng build --configuration production

  post_build:
    commands:
      - echo Build completed on `date`
      # Optional: Copy build output to a dist folder with specific name
      - cp -r dist/* ./build-output/

artifacts:
  files:
    - '**/*'
  base-directory: build-output
  discard-paths: no
