version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - npm install
      - npm audit fix  # Fix vulnerabilities
  build:
    commands:
      - ng build --configuration production  # Updated syntax

artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'